site_name: Meatcorps Raylib-cs Notes
site_description: Unofficial practical notes for building games and tools with Raylib-cs and C#.
site_author: Dennis Steffen
site_url: https://docs.meatcorps.nl/

nav:
  - Home: index.md
  - Raylib-cs:
    - Overview: raylib-cs.md
    - Getting Started Hello World!: raylibcs/gettingstarted.md
    - Practical Debugging Tips: raylibcs/debugging.md
    - Textures for 2D games and simple animations: raylibcs/textures.md
    - Post-processing stack: raylibcs/postprocessing.md
theme:
  name: mkdocs
  language: en
  user_color_mode_toggle: true
  color_mode: auto

extra_css:
  - stylesheets/meatcorps.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true