site_name: Meatcorps Raylib-cs Notes
site_description: Unofficial practical notes for building games and tools with Raylib-cs and C#.
site_author: Dennis Steffen
site_url: https://docs.meatcorps.nl/

nav:
  - Home: index.md
  - Raylib-cs:
    - Overview: raylib-cs.md
    - Raylib-cs 7.0.2 to 8.0.0 Upgrade to Raylib 6.0!: raylibcs/release55to60.md
    - Raylib-cs Getting Started Hello World!: raylibcs/gettingstarted.md
    - Raylib-cs Practical Debugging Tips: raylibcs/debugging.md
    - Raylib-cs Textures for 2D games and simple animations: raylibcs/textures.md
    - Raylib-cs Post-processing stack: raylibcs/postprocessing.md
  - R3D.NET:
    - R3D.NET 0.9.1 unofficial Cheatsheet: r3dnet/r3dnetcheatsheet.md
theme:
  name: mkdocs
  language: en
  user_color_mode_toggle: true
  color_mode: auto

extra_css:
  - stylesheets/meatcorps.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true